synchronize workflows with nodes, as far as appropriate

diff --git a/.github/workflows/develop.yml b/.github/workflows/develop.yml
--- a/.github/workflows/develop.yml
+++ b/.github/workflows/develop.yml
@@ -5,14 +5,20 @@ name: Develop - Build and Deploy Snapshot
 on:
   push:
     branches: [ develop ]
+  workflow_dispatch:
 
 jobs:
   build:
 
     runs-on: ubuntu-latest
 
+    env:
+      MVNCMD: mvn -B -ntp -s ${{ github.workspace }}/.github/settings-istrepo.xml  -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
+
     steps:
     - uses: actions/checkout@v3
+      with:
+        fetch-depth: 3
 
     - name: Set up JDK 11
       uses: actions/setup-java@v3
@@ -20,27 +26,53 @@ jobs:
         java-version: '11'
         distribution: 'temurin'
         cache: maven
+        maven-version: 3.8.7
+
+    - name: Dump event context for debugging
+      continue-on-error: true  # Debugging output only, and this annoyingly fails when the commit messge has a (
+      run: |
+        echo '${{ github.event_name }} for ${{ github.ref_type }} ${{ github.ref_name }} or ${{ github.event.ref }}'
+        # https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#push
+        echo 'github.event:'
+        echo '${{ toJSON(github.event) }}'
+
+    - name: Dump github context
+      continue-on-error: true  # Debugging output only, and this annoyingly fails when the commit message has a (
+      run: |
+          echo '${{ toJSON(github) }}'
+
+    - name: Git & Maven Status
+      run: |
+        git status --untracked-files --ignored
+        git log -3 --no-color
+        $MVNCMD -version
+
+    - name: Mvn Effective POM
+      run: $MVNCMD -P develop -N help:effective-pom
+
+    - name: Mvn Effective Settings
+      run: $MVNCMD -P develop -N help:effective-settings
 
     - name: Build with Maven
       # When parent-2:1.7 is active, -P ensureSnapshots will do a sanity check of the version number
       # We try several times since unfortunately there are sporadic startup problems in the integration tests :-(
       run: |
-        ( mvn -s .github/settings-istrepo.xml -P ensureSnapshots -B install && echo 1st run success ) || \
-        ( mvn -s .github/settings-istrepo.xml -P ensureSnapshots -B install && echo 2nd run success ) || \
-        ( mvn -s .github/settings-istrepo.xml -P ensureSnapshots -B install && echo 3rd run success )
+        ( $MVNCMD -P ensureSnapshots,test -B verify$MVNCMD -P ensureSnapshots,test -B verify && echo 1st run success ) || \
+        ( $MVNCMD -P ensureSnapshots,test -B verify && echo 2nd run success ) || \
+        ( $MVNCMD -P ensureSnapshots,test -B verify && echo 3rd run success )
 
     - name: Sanitycheck version before deploying
       run: |
         echo "Version: "
-        mvn -s .github/settings-istrepo.xml help:evaluate -Dexpression=project.version -q -DforceStdout
-        mvn -s .github/settings-istrepo.xml help:evaluate -Dexpression=project.version -q -DforceStdout | egrep -- '-SNAPSHOT$' > /dev/null || exit 1
+        $MVNCMD help:evaluate -Dexpression=project.version -q -DforceStdout
+        $MVNCMD help:evaluate -Dexpression=project.version -q -DforceStdout | egrep -- '-SNAPSHOT$' > /dev/null || exit 1
         # unfortunately, this would require a snapshot parent if just called from the command line, so we cannot use it: :-(
         # mvn org.apache.maven.plugins:maven-enforcer-plugin:3.0.0:enforce -Drules=requireSnapshotVersion
 
     - name: Deploy with Maven
       # We don't do docker pushes as we don't currently (as of 4/22) have an automatic solution for multi architecture builds
       # Compare also https://github.com/actions/virtual-environments/issues/2187 (M1 support for github actions)
-      run: mvn -s .github/settings-istrepo.xml -Ddocker.skip.push=true -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -P develop -B deploy
+      run: $MVNCMD -P develop deploy
       env:
         NEXUS_BUILD_USER: ${{ secrets.NEXUS_BUILD_USER }}
         NEXUS_BUILD_PASSWD: ${{ secrets.NEXUS_BUILD_PASSWD }}
